name: Checks

on:
  pull_request:
    paths-ignore:
      - README.md
      - CHANGELOG.md
      - LICENSE
  push:
    branches: main
    paths-ignore:
      - README.md
      - CHANGELOG.md
      - LICENSE

env:
  CARGO_INCREMENTAL: 0
  RUSTFLAGS: "-Dwarnings"

jobs:
  clippy:
    runs-on:
      - ubuntu-latest
      - macOS
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toochain@v1
        with:
          toolchain: 1.60.0
          components: clippy
          override: true
          profile: minimal
      - run: cargo clippy --all -- -D warnings

#  rustfmt:
#    runs-on: ubuntu-latest
#    - uses: actions/checkout@v2
#    - uses: actions-rs/toochain@v1
#      with:
#        toolchain: stable
#        components: clippy
#        override: true
#        profile: minimal
#    - uses: actions-rs/cargo@v1
#      with:
#        command: fmt
#        args: --all -- --check
#  build:
#    runs-on: ubuntu-latest
#    strategy:
#      matrix:
#        rust:
#          - stable
#    steps:
#      - uses: actions/checkout@v2
#      - uses: actions-rs/toolchain@v1
#        with:
#          profile: minimal
#          toolchain: ${{ matrix.rust }}
#          override: true
#      - run: cargo build --no-default-features --features=rust
#      - run: cargo build --no-default-features --features=openssl
#      - run: cargo build --no-default-features --features=gmp
#  test:
#    runs-on: ubuntu-latest
#    strategy:
#      matrix:
#        include:
#          - target: i686-unknown-linux-gnu
#            rust: stable
#            deps: sudo apt update && sudo apt install gcc-multilib
#          - target: x86_64-unknown-linux-gnu
#            rust: stable
#    steps:
#      - uses: actions/checkout@v2
#      - uses: actions-rs/toolchain@v1
#        with:
#          profile: minimal
#          toolchain: ${{ matrix.rust }}
#          target: ${{ matrix.target }}
#          override: true
#      - run: ${{ matrix.deps }}
#      - run: cargo check --target ${{ matrix.target }} --no-default-features --features=rust
#      - run: cargo check --target ${{ matrix.target }} --no-default-features --features=openssl
#      - run: cargo check --target ${{ matrix.target }} --no-default-features --features=gmp
#      - run: cargo test --target ${{ matrix.target }} --no-default-features --features=rust
#      - run: cargo test --target ${{ matrix.target }} --no-default-features --features=openssl
#      - run: cargo test --target ${{ matrix.target }} --no-default-features --features=gmp
#
